### ISSUE TITLE
Mocks for covariances for a reference cosmology?

### ISSUE THREAD

**Issue by neyrinck** [ANSalcedo/Beyond2ptMock#1]
Hi, excited about the data challenge!

I have a question/suggestion: are there any plans to release/specify a set of mocks for analysis to use e.g. for covariances, made in the same way as what you released? I'm guessing not; we don't know how the Universe populated dark matter haloes with galaxies! It's fair enough to get a full mock as the Universe presents us with.

But I also think that an additional set of blind mocks would be interesting, that have associated with them a large ensemble of mocks generated in the same way, with cosmological parameters that are given (unblinded). And a set of mocks with slightly different cosmological parameters of interest, that could be used to estimate derivatives of measured statistics with respect to those parameters (at least, sigma_8). (this would be a lot of data! practically, it would probably be less than all that!) The main reason I'm thinking that would be useful would be to decouple the inherent statistical power of a method from other more practical matters: choices of mock catalogs, ways of estimating how galaxies occupy haloes, etc. used for covariance estimates. Also, maybe more important, in the past these data challenges have inspired me to think of new techniques. Providing/specifying mocks for covariances would make it easier and faster to try out a new method for which substantial groundwork might not already exist.

I'm not taking into account here the difficulty in preparing the data etc.; just brainstorming something that seems useful!

**Comment by ANSalcedo** [comment]
Hi!  The covariance requirements of different analyses may differ quite substantially, so we decided to only provide mock data in this initial challenge. We’d be happy to discuss how analysts might adapt some of the publicly available simulation suites geared towards covariance estimation to this galaxy sample.

In the short term we are not planning on generating mocks with single-cosmology-parameter variations, but in the longer term these are something that is feasible for us to compute and release if there's sufficient interest.
