### ISSUE TITLE
Box size

### ISSUE THREAD

**Issue by KuanWang-Astro** [ANSalcedo/Beyond2ptMock#2]
Hi! I'm a bit confused about the box sizes, the README file says that the box is from a (1.3Gpc/h)^3 snapshot, but with a periodic boundary condition with box length 1.1Gpc/h, are there two different boxes involved or is it the same box but truncated?

Thanks a lot!

**Comment by elikrause** [comment]
The box length is 1.1 Gpc/h, we just quoted the approximate volume as ~1.3 (Gpc/h)^3.

**Comment by KuanWang-Astro** [comment]
I see, thanks! I mistook 1.3 as the value of the length instead of the volume.
