### ISSUE TITLE
Alternative number density catalogs?

### ISSUE THREAD

**Issue by KuanWang-Astro** [ANSalcedo/Beyond2ptMock#3]
Hi! We are considering an analysis using the Molino Suite (https://changhoonhahn.github.io/molino/current/) to interpolate cosmology, but those have a galaxy number density of n_g ~ 1.63x10^-4 h^3 Mpc^-3, which is about half of the data challenge mocks. Would it be possible to generate and release catalogs with this number density? Or would it be possible to add galaxy luminosity to the mocks so that we could apply further selections ourselves? Also, as a clarification, are the samples in the mocks luminosity threshold samples? Thank you very much!

**Comment by archaeo-pteryx** [comment]
Hi Kuan, we released the real-space lower number density mock (F mock), with n_g ~ 1e-4 (Mpc/h)^{-3}. I think it meets your requirement.
These mocks are just based on the HOD prescription, and hence we don't explicitly impose any luminosity on galaxies.

**Comment by KuanWang-Astro** [comment]
Thank you! We were hoping for a closer number density, but we can also work with what's available.
